[package]
name = "srun-app"
version = "1.1.1"
description = "深澜校园网自动登录 GUI（Tauri + React）"
edition = "2021"

[lib]
name = "srun_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
srun-core = { path = "../../srun-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
